apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  labels:
    usage: jenkins
spec:
  capacity:
    storage: 5Gi
  storageClassName: azurefile
  accessModes:
    - ReadWriteOnce
  azureFile:
    secretName: azure-secret
    shareName: jenkins
    readOnly: false