apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar
spec:
  capacity:
    storage: 5Gi
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  azureFile:
    secretName: azure-secret
    shareName: sonarqube
    readOnly: false