apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.11.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: sonar
  name: sonar
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sonar
    spec:
      containers:
      - env:
        - name: SONARQUBE_JDBC_PASSWORD
          value: s0nArqub3
        - name: SONARQUBE_JDBC_URL
          value: jdbc:sqlserver://sql;databaseName=sonar
        - name: SONARQUBE_JDBC_USERNAME
          value: sonar
        image: sonar
        name: sonar
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
status: {}
