apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.8.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: sonar
  name: sonar
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sonar
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      containers:
      - image: sonarqube:lts-alpine
        name: sonar
        ports:
        - containerPort: 9000
        - containerPort: 9092
status: {}




