apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.8.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: vsts
  name: vsts
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: vsts
    spec:
      containers:
      - image: vsts
        name: vsts
        resources: {}
      restartPolicy: Always
status: {}
