FROM azuresdk/azure-cli-python

VOLUME [ "/mnt/jmg" ]
ENV AZURE_STORAGE_ACCOUNT=frankenstorage
ENV AZURE_STORAGE_KEY=koQHr72hrRaBYPF9kT5F+XfeIZ8fhp7nt6DuyQnRmnzTrVBukCOMxgcdtsjKx+zUztzxbf1rvUwERnvqimfY7g==


