apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.11.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: azurite
  name: azurite
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: azurite
    spec:
      containers:
      - env:
        - name: executable
          value: blob
        image: arafato/azurite
        name: azurite
        ports:
        - containerPort: 10000
        resources: {}
        volumeMounts:
        - mountPath: /opt/azurite/folder
          name: azurite-claim0
      restartPolicy: Always
      volumes:
      - name: azurite-claim0
        persistentVolumeClaim:
          claimName: azurite-claim0
status: {}
